create table public.kca_incidents (
  id bigint generated by default as identity primary key,
  type text not null,
  location text not null,
  description text not null,
  reporter_name text not null default 'Anonymous',
  phone text not null default 'N/A',
  is_sos boolean not null default false,
  status text not null default 'new' check (status in ('new', 'acknowledged', 'dispatched', 'resolved')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.kca_incidents enable row level security;
create policy "Anyone can submit incidents" on public.kca_incidents for insert to anon with check (true);
create policy "Anyone can read incidents" on public.kca_incidents for select to anon using (true);
create policy "Anyone can update incident status" on public.kca_incidents for update to anon using (true) with check (true);
